### ISSUE TITLE
Linesegmenter returns null on some input images (Stacktrace+input file included)

### ISSUE THREAD

**Issue by ghost** [kirksaunders/subtitle-ocr-console#2]
Tried to convert SUP, crashed at 90%.
Binarizer failed to convert input image at hardcoded default threshold of 0.5, resulting in a mostly blank bitmap.

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Dimensions must be non-negative Arg_ParamName_Name
  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   at Microsoft.ML.OnnxRuntime.Tensors.Tensor`1..ctor(ReadOnlySpan`1 dimensions, Boolean reverseStride)
   at Microsoft.ML.OnnxRuntime.Tensors.DenseTensor`1..ctor(ReadOnlySpan`1 dimensions, Boolean reverseStride)
   at subtitle_ocr_console.OCR.InferenceModel.Infer(List`1 images, LanguageModel languageModel) in E:\GITHUB\subtitle-ocr-console\OCR\InferenceModel.cs:line 57
   at subtitle_ocr_console.ProgramEntry.ConvertPGS(FileInfo pgsPath, FileInfo srtPath, String modelStr) in E:\GITHUB\subtitle-ocr-console\Program.cs:line 423
[binarizer.zip](https://github.com/kirksaunders/subtitle-ocr-console/files/13395085/binarizer.zip)
![source](https://github.com/kirksaunders/subtitle-ocr-console/assets/130250788/3f60fe9e-e5b2-4f02-9a1a-1f5089f09d30)

**Comment by ghost** [comment]
Edit: I think there is something more awry, because I also get very funny text output where it doesnt throw an exception.
Here's an excerpt, from the same SUP file as the one above:

> 1
> 00:01:56,971 --> 00:01:58,431
> yfffftLJryiJ
> 
> 2
> 00:02:05,063 --> 00:02:07,148
> -frfrfrJ' f ytyfjck
> 
> 3
> 00:02:14,072 --> 00:02:17,241
> Crf, rtt trt trkf tyiff
> 
> 4
> 00:02:17,367 --> 00:02:19,994
> 4pyrrf t iff ttttt ir, ffr
> tr rury ftyr rfyjk,

Sorry, I just noticed that right now, otherwise I have had it included in the OP
Here is one of the more recognizable ones, but they basically all look the same after binarization:
![binar30](https://github.com/kirksaunders/subtitle-ocr-console/assets/130250788/70a0d7d8-216c-49c6-b521-14093ea5a5ef)

**Comment by kirksaunders** [comment]
Were you using mainline? This looks similar to a bug I fixed a while back ([in this commit](https://github.com/kirksaunders/subtitle-ocr-console/commit/420465ed6255dad32ad693296b918b3020eb639d)). The fix isn't on mainline.

Can you try the [better-results](https://github.com/kirksaunders/subtitle-ocr-console/tree/better-results) branch to see whether it fixes your issue? As an added bonus, that branch is faster, fixes various bugs, has a more accurate model, and has slightly improved progress bars and documentation. I really need to merge it into mainline...

**Comment by ghost** [comment]
Oh, yep i was using main. I'll try the other one, thanks! This input SUP is strange anyways. The only good binarizing result I get is by using the Posterize method in Paint Shop Pro IX with a threshold of 15, but for some reason I couldnt recreate that as a new binarizer method. Guess I need some sleep
